version: '3.4'
services:
    master:
        container_name: jenkins-master
        image: 'mateothegreat/docker-alpine-gcloud-kubectl:latest'
        volumes:
          - '$PWD/service_account.json:/service_account.json'
        restart: always
        environment: 
          - GCLOUD_KEY_FILE=/service_account.json
          - GCLOUD_PROJECT=managix-devops
          - GCLOUD_ZONE=asia-southeast1-a
        command:
          - gcloud projects list